/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.model.FilaPaciente;
import br.com.rogerio.model.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FilaView extends javax.swing.JFrame {

    FilaPaciente fila;
    Paciente paciente;
    Paciente[] pac = new Paciente[5];

    /**
     * Creates new form FilaView
     */
    public FilaView() {
        initComponents();

        jTextAreaSaida.setLineWrap(true);
        fila = new FilaPaciente();
    }

    private void preencherFichaDoPaciente() {

        paciente = new Paciente();
        paciente.setNome(jTextFieldNomePaciente.getText());
        paciente.setCpf(jTextFieldCpfPaciente.getText());
        paciente.setTelefone(jTextFieldTelefonePaciente.getText());
        paciente.setEmail(jTextFieldEmailPaciente.getText());

    }
    
    private void limpaCampos(){
        jTextFieldNomePaciente.setText("");
        jTextFieldNomePaciente.requestFocus();
    }
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilaDePacientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomePaciente = new javax.swing.JTextField();
        jTextFieldCpfPaciente = new javax.swing.JTextField();
        jTextFieldTelefonePaciente = new javax.swing.JTextField();
        jTextFieldEmailPaciente = new javax.swing.JTextField();
        jButtonInserir = new javax.swing.JButton();
        jButtonChamar = new javax.swing.JButton();
        jButtonStatusDaFila = new javax.swing.JButton();
        jButtonPróximoAserChamado = new javax.swing.JButton();
        jButtonTamanhoDaFila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projeto Fila - Exercicio 01 - Paciente na Fila do Consultório.");
        setResizable(false);

        jLabel1.setText("Consultório Médico");

        jLabel2.setText("Nome do paciente:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Email:");

        jTextFieldNomePaciente.setText("Rogério Tadeu dos Reis ");

        jTextFieldCpfPaciente.setText("111.222.333.44");

        jTextFieldTelefonePaciente.setText("62-1234-1234");

        jTextFieldEmailPaciente.setText("rogerio@gmail.com");

        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonChamar.setText("Chamar");
        jButtonChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamarActionPerformed(evt);
            }
        });

        jButtonStatusDaFila.setText("Status da Fila");
        jButtonStatusDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusDaFilaActionPerformed(evt);
            }
        });

        jButtonPróximoAserChamado.setText("Próximo");
        jButtonPróximoAserChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPróximoAserChamadoActionPerformed(evt);
            }
        });

        jButtonTamanhoDaFila.setText("Tamanho da Fila");
        jButtonTamanhoDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamanhoDaFilaActionPerformed(evt);
            }
        });

        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jTextAreaSaida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTextAreaSaida);

        javax.swing.GroupLayout jPanelFilaDePacientesLayout = new javax.swing.GroupLayout(jPanelFilaDePacientes);
        jPanelFilaDePacientes.setLayout(jPanelFilaDePacientesLayout);
        jPanelFilaDePacientesLayout.setHorizontalGroup(
            jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1))
                    .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jButtonChamar)
                            .addComponent(jButtonStatusDaFila)
                            .addComponent(jButtonPróximoAserChamado)
                            .addComponent(jButtonTamanhoDaFila)
                            .addComponent(jButtonInserir))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(jTextFieldNomePaciente)
                            .addComponent(jTextFieldCpfPaciente)
                            .addComponent(jTextFieldTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmailPaciente))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelFilaDePacientesLayout.setVerticalGroup(
            jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEmailPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFilaDePacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFilaDePacientesLayout.createSequentialGroup()
                        .addComponent(jButtonInserir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChamar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStatusDaFila)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPróximoAserChamado)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTamanhoDaFila))
                    .addComponent(jScrollPane1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaDePacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFilaDePacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        // TODO add your handling code here:
        try {
            preencherFichaDoPaciente();
            fila.enqueue(paciente);
            limpaCampos();
            jTextAreaSaida.setText(paciente.toString() + "\nInserido na fila: " + fila.size());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jButtonChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamarActionPerformed
        // TODO add your handling code here:
        try {
            fila.dequeue();
            jTextAreaSaida.setText("\nQuantidade de paciente(s) = " + fila.size());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonChamarActionPerformed

    private void jButtonStatusDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            if (fila.isFull()) {
                jTextAreaSaida.setText("A fila de pacientes está cheia!\n");
            } else if (fila.isEmpty()) {
                jTextAreaSaida.setText("A fila de pacientes está vazia!\n");
            } else {
                jTextAreaSaida.setText("A fila está com " + fila.size() + " pacientes!\n");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonStatusDaFilaActionPerformed

    private void jButtonPróximoAserChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPróximoAserChamadoActionPerformed
        // TODO add your handling code here:
        try {
            jTextAreaSaida.setText("Próximo paciente da fila: " + fila.peek().getNome());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonPróximoAserChamadoActionPerformed

    private void jButtonTamanhoDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamanhoDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            jTextAreaSaida.setText("Tamanho da fila de paciente(s): " + fila.size());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Atenção!!!\n" + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonTamanhoDaFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChamar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonPróximoAserChamado;
    private javax.swing.JButton jButtonStatusDaFila;
    private javax.swing.JButton jButtonTamanhoDaFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelFilaDePacientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldCpfPaciente;
    private javax.swing.JTextField jTextFieldEmailPaciente;
    private javax.swing.JTextField jTextFieldNomePaciente;
    private javax.swing.JTextField jTextFieldTelefonePaciente;
    // End of variables declaration//GEN-END:variables
}
